### ISSUE TITLE
Unhandled rejection Error: socket hang up 

### ISSUE THREAD

**Issue by GeoffreyPlitt** [mindblaze/streaming-s3#7]
How do I debug this?

  Unhandled rejection Error: socket hang up 
      at SecurePair.error (tls.js:1011:23) 
      at EncryptedStream.CryptoStream._done (tls.js:703:22) 
      at CleartextStream.read [as _read] (tls.js:499:24) 
      at CleartextStream.Readable.read (_stream_readable.js:341:10) 
      at EncryptedStream.onCryptoStreamFinish (tls.js:304:47) 
      at EncryptedStream.g (events.js:180:16) 
      at EncryptedStream.emit (events.js:117:20) 
      at finishMaybe (_stream_writable.js:360:12) 
      at endWritable (_stream_writable.js:367:3) 
      at EncryptedStream.Writable.end (_stream_writable.js:345:5) 
      at EncryptedStream.CryptoStream.end (tls.js:641:31) 
      at Socket.onend (_stream_readable.js:502:10) 
      at Socket.g (events.js:180:16) 
      at Socket.emit (events.js:117:20) 
      at _stream_readable.js:944:16 
      at process._tickDomainCallback (node.js:486:13)

**Comment by talha-asad** [comment]
This is generally a network error. Perhaps check your internet connection.

**Comment by talha-asad** [comment]
Please give code so i can reproduce this.

**Comment by talha-asad** [comment]
Closed due to no response, open again if you still have problems.
